// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8rnafQQbGjo2YC6NklWkt-VPaOEGx0OU',
    appId: '1:666976149522:web:c3a2f4539c9b807af138cb',
    messagingSenderId: '666976149522',
    projectId: 'virtual-queue-a4422',
    authDomain: 'virtual-queue-a4422.firebaseapp.com',
    storageBucket: 'virtual-queue-a4422.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6sCPkpjHtTvuWEjPVYBQczEDUxyrUXOY',
    appId: '1:666976149522:android:4e2b46f7d855ea46f138cb',
    messagingSenderId: '666976149522',
    projectId: 'virtual-queue-a4422',
    storageBucket: 'virtual-queue-a4422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRwA6-ZjnyJ3jTCLdXDw6ycRj7bpIHYDU',
    appId: '1:666976149522:ios:a26fe5468f838397f138cb',
    messagingSenderId: '666976149522',
    projectId: 'virtual-queue-a4422',
    storageBucket: 'virtual-queue-a4422.firebasestorage.app',
    iosBundleId: 'com.example.virtualQueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRwA6-ZjnyJ3jTCLdXDw6ycRj7bpIHYDU',
    appId: '1:666976149522:ios:a26fe5468f838397f138cb',
    messagingSenderId: '666976149522',
    projectId: 'virtual-queue-a4422',
    storageBucket: 'virtual-queue-a4422.firebasestorage.app',
    iosBundleId: 'com.example.virtualQueue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8rnafQQbGjo2YC6NklWkt-VPaOEGx0OU',
    appId: '1:666976149522:web:e867f7bffe80b1ddf138cb',
    messagingSenderId: '666976149522',
    projectId: 'virtual-queue-a4422',
    authDomain: 'virtual-queue-a4422.firebaseapp.com',
    storageBucket: 'virtual-queue-a4422.firebasestorage.app',
  );
}
